# Ultimate ML DL BootCamp- NumPy Assignment



#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print("Numpy version: ",np.__version__)
print("Numpy configuration \n")
np.show_config()


#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
null_vect = np.zeros(10)
print(null_vect)

#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
demo = np.array([1,2,3])
print("Each element size :",demo.itemsize)
print("Total size :",demo.nbytes)

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
# python -m pydoc numpy.add

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
vect = np.zeros(10);
vect[4]=1
print(vect)

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
vect = np.arange(10,50)
print(vect)

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
vect = np.arange(10,20)
print("Original :",vect)
vect = vect[::-1]
print("Reverse :",vect)

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
mat = np.arange(0,9).reshape(3,3)
print(mat)

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
mat = np.array([1,2,0,0,4,0])
idx = mat.nonzero()
print(idx)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
identity_mat = np.identity(3,dtype=int)
print(identity_mat)

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
random_array_3d = np.random.random((3, 3, 3))
print(random_array_3d)

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
mat = np.random.rand(10,10)
print(mat)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
range = np.random.default_rng()
vect = range.integers(low=11,high=99,size=30)
print(vect)

meanVal = np.mean(vect)
print(meanVal)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
r = 5
c = 5
mat = np.ones((r,c),dtype=int)

mat[1:r-1,1:c-1]=0
print(mat)

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Original Matrix:\n",mat)

newArr = np.pad(mat,pad_width=1,mode='constant',constant_values=0)
print("Padded Matrix:\n",newArr)

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
mat = np.diag(1+np.arange(4),k=-1)
print(mat)

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
import numpy as np
mat = np.zeros((8,8),dtype=int)

mat[0::2,1::2] = 1
mat[1::2,0::2] = 1

print(mat)

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
(1,5,3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
r1 = [0,1]*4
r2 = [1,0]*4
chk = np.tile([r1,r2],(4,1))
print(chk)

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
mat = np.random.rand(5,5)
print(mat)

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
color_type = np.dtype([
    ('r',np.uint8),
    ('g',np.uint8),
    ('b',np.uint8),
    ('a',np.uint8)
])
colors = np.array([
    (255,0,0,255),
    (0,255,0,255),
    (0,0,255,255),
    (255,255,255,128)
],dtype=color_type)

print(colors['r'])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
a = np.random.rand(5,3)
b = np.random.rand(3,2)
print(np.dot(a,b))

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
arr = np.arange(10)
print(arr)
arr[3:9]=-arr[3:9]
print(arr)

#### 26. What is the output of the following script? (★☆☆)
```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
9
10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
# Z**Z  True
# 2 << Z >> 2 True
# Z <- Z False
# 1j*Z True
# Z/1/1 True
# Z<Z>Z False

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
import numpy as np
#nan
#0
print(np.array(0) / np.array(0))
(print(np.array(0) // np.array(0)))
print(np.array([np.nan]).astype(int).astype(float))

#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
Z = np.array([1.2, 1.5, -1.2, -1.5, 0.0])
rounded = np.round(Z)
print(rounded)

#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
a = np.array([1, 2, 3, 4, 5])
b= np.array([4,5,6,7,8])
print(np.intersect1d(a,b))

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
# np.seterr(all="ignore")

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
today = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')

print("Today:", today)
print("Yesterday:", yesterday)
print("Tomorrow:", tomorrow)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
date= np.arange(
    np.datetime64('2016-07-01'),
    np.datetime64('2016-08-01'),
    np.timedelta64(1,'D')
)
print(date)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
a = np.random.rand(5,5)
b = np.random.rand(5,5)

a*=-0.5
a*=(a+b)
print(a)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
mat = np.random.rand(5,5)*10
print(mat)

#np.floor
type1 = np.floor(mat)
print(type1)

#np.astype(int)
type2 = mat.astype(int)
print(type2)

#np.trunc
type3 = np.trunc(mat)
print(type3)

#integer division
type4 = mat//1
print(type4)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
mat = np.tile(np.arange(5), (5, 1))
print(mat)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
def generate():
    for i in range(10):
        yield i
Z = np.fromiter(generate(), dtype=int)
print(Z)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
mat =  np.arange(1, 11) / 11
print(mat)

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
mat = np.random.rand(10)*10
mat = np.sort(mat)
print(mat)

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
mat = np.array([1,2,3,4,5])
total = sum(mat)
print(total)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [ ]:
a = np.random.randint(0,5,5)
b = np.random.randint(0,5,5)
print(np.array_equal(a,b))

#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr.flags.writeable = False
print(arr)
arr[0]=10
print(arr)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
mat = np.random.randint(0,10,(10,2))
print(mat)

x = mat[:,0]
y = mat[:,1]

r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)

polar = np.column_stack((r, theta))
print(polar)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
import numpy as np
vec = np.random.random(10)*10
idx = np.argmax(vec)
print("Original vector:",vec)
vec[idx] = 0
print("\nModified vector:",vec)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [ ]:
x = np.array([1.0,2.0,3.0])
y = np.array([4.0,6.0])

c = 1.0/(x[:,None]-y[None,:])
print(c)

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

In [ ]:
int_types= [np.int8,np.int16,np.int32,np.int64,
            np.uint8,np.uint16,np.uint32,np.uint64]
for i in int_types:
    info = np.iinfo(i)
    print(i.__name__," Min =",info.min," Max =",info.max)

#### 49. How to print all the values of an array? (★★☆)

In [ ]:
arr = np.arange(10)
print(arr)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
vec = np.array([0.1, 2.3, 4.7, 6.9, 9.2])
sca = 5.0

closest_value = vec[np.abs(vec-sca).argmin()]
print(closest_value)


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
dtype = [
    ('position', [('x','f4'),('y','f4')]),
    ('color',[('r','u1'),('g','u1'),('b','u1')])
]
arr = np.zeros(3,dtype=dtype)
arr['position']['x']= [0.0,1.0,2.0]
arr['position']['y']= [0.0,1.0,2.0]
arr['color']['r'] = [255,0,0]
arr['color']['g'] = [0,255,0]
arr['color']['b'] = [0,0,255]
print(arr)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
vec = np.random.rand(100,2)*20
diff = np.diff(vec,axis=0)
distances = np.linalg.norm(diff, axis=1)

print(distances)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5],dtype=np.float32)
arr = arr.astype(np.int32)
print(arr)

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
import numpy as np
data = np.genfromtxt('file.txt', delimiter=',', filling_values=0)
print(data)

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])

for i, val in np.ndenumerate(arr):
    print("Index:",i," Value:",val)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [ ]:
import numpy as np


def gaussian_2d(size=5, sigma=1.0, center=None):
    if center is None:
        center = (size / 2, size / 2)
    
    x = np.linspace(0, size - 1, size)
    y = np.linspace(0, size - 1, size)
    X, Y = np.meshgrid(x, y)
    
    gaussian = np.exp(-((X - center[0])**2 + (Y - center[1])**2) / (2 * sigma**2))
    
    return gaussian

result = gaussian_2d(size=10, sigma=2.0)
print(result)


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [33]:
import numpy as np

rows, cols = 5, 5
p = 10 

arr = np.zeros((rows, cols))

idx = np.random.choice(rows * cols,p, replace=False)
arr.flat[idx] = 1

print(arr)


[[0. 0. 0. 1. 1.]
 [0. 0. 0. 1. 0.]
 [0. 1. 1. 0. 1.]
 [1. 0. 0. 1. 0.]
 [0. 0. 1. 1. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [34]:
import numpy as np

mat = np.random.rand(5, 4) * 10
print("Original matrix:")
print(mat)

mat_centered = mat - mat.mean(axis=1, keepdims=True)
print("\nMatrix after subtracting row means:")
print(mat_centered)

print("\nRow means after subtraction (should be ~0):")
print(mat_centered.mean(axis=1))


Original matrix:
[[5.90735403 0.82946212 5.61206645 3.87420259]
 [8.16128157 8.03361939 4.38435908 0.0469865 ]
 [5.55489636 0.62313689 0.89535437 9.26281749]
 [3.76421277 4.32766575 6.81614291 8.23892921]
 [6.41231591 2.35851726 2.81648619 3.28004127]]

Matrix after subtracting row means:
[[ 1.85158273 -3.22630918  1.55629516 -0.18156871]
 [ 3.00471993  2.87705775 -0.77220255 -5.10957513]
 [ 1.47084509 -3.46091439 -3.18869691  5.17876621]
 [-2.02252489 -1.45907191  1.02940525  2.45219155]
 [ 2.69547575 -1.3583229  -0.90035397 -0.43679888]]

Row means after subtraction (should be ~0):
[-4.44089210e-16 -4.44089210e-16 -2.22044605e-16  2.22044605e-16
 -6.66133815e-16]


#### 59. How to sort an array by the nth column? (★★☆)

In [6]:
import numpy as np

arr = np.array([
    [3, 2, 1],
    [1, 3, 2],
    [2, 1, 3]
])

n=0
print("Original Array: ")
print(arr)
print("Sorted nth column: ")
sorted_arr = arr[arr[:,n].argsort()]
print(sorted_arr)

Original Array: 
[[3 2 1]
 [1 3 2]
 [2 1 3]]
Sorted nth column: 
[[1 3 2]
 [2 1 3]
 [3 2 1]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [9]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
null_cols = np.any(np.isnan(arr), axis=0)
print(null_cols)

[False False False]


#### 61. Find the nearest value from a given value in an array (★★☆)

In [13]:
arr = np.array([10, 22, 35, 47, 59])
target = 40
nearest = arr[np.abs(arr-target).argmin()]
print(nearest)


35


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [18]:
A = np.array([[1, 2, 3]])      
B = np.array([[4], [5], [6]])  

res = np.empty((3,3),dtype=int)

it = np.nditer(
    [A , B , res],
    flags=['multi_index'],
    op_flags=[['readonly'],['readonly'],['writeonly']]
)

for a,b,r in it:
    r[...] =a+b
print(res)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
class ArrayWithName:
    def __init__(self,array,name):
        self.array = array
        self.name = name

arr = ArrayWithName(
    array = np.array([1,2,3,4,5]),
    name = "MyArray"
)

print(arr.array)
print(arr.name)

[1 2 3 4 5]
MyArray


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [25]:
arr = np.array([1, 2, 3, 4, 5])
idx = [1,1, 3, 4]
np.add.at(arr,idx, 1)
print(arr)

[1 4 3 5 6]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [ ]:
x = np.array([1, 2, 3, 4])
i = np.array([0, 1, 1, 3])

f = np.zeros(5, dtype=int)

np.add.at(f, i, x)

print(f)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [2]:
img = np.array([
    [[255, 0, 0], [0, 255, 0]],
    [[255, 0, 0], [0, 0, 255]]
], dtype=np.uint8)

pixels = img.reshape(-1, 3)

unique_colors = np.unique(pixels, axis=0)

no = len(unique_colors)

print("Unique colors:")
print(unique_colors)
print("Number of unique colors:", no)


NameError: name 'np' is not defined

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [3]:
import numpy as np

arr = np.random.rand(2, 3, 4, 5)
res = arr.sum(axis=(2, 3))
print(res)


[[ 8.02317807  9.85255362  9.4970844 ]
 [ 8.32009806 10.7793442   9.487816  ]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [10]:
import numpy as np

D = np.array([10, 20, 30, 40, 50, 60])
S = np.array([0, 0, 1, 1, 1, 2])

sums = np.bincount(S,weights=D)
count = np.bincount(S)
print("Means:",sums/count)

Means: [15. 40. 60.]


#### 69. How to get the diagonal of a dot product? (★★★)

In [ ]:
A = np.random.rand(5, 3)*5
B = np.random.rand(3, 5)*5

diag = np.sum(A * B.T, axis=1)
print(diag)

[51.94166243 86.06076883 48.60945355 81.73806454 89.54284712]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [ ]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])

n = 3 
y = np.zeros(len(x) * (n + 1), dtype=x.dtype)
y[::n + 1] = x

print(y)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

In [28]:
a = np.random.rand(5,5,3)
b = np.random.rand(5,5)

res = a*b[:,:,np.newaxis]
print(res.shape)

(5, 5, 3)


#### 72. How to swap two rows of an array? (★★★)

In [58]:
a = np.arange(12).reshape(3,4)
print(a)

tmp = a[2:,:].copy()
a[2:, :] = b
a[1:2, :] = tmp
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 8  9 10 11]
 [ 4  5  6  7]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [59]:
import numpy as np

triangles = np.array([
    [0, 1, 2],
    [2, 3, 0],
    [1, 2, 3],
    [3, 4, 1],
    [4, 5, 3],
    [5, 6, 4],
    [6, 7, 5],
    [7, 8, 6],
    [8, 9, 7],
    [9, 0, 8]
])

edges = np.vstack([
    triangles[:, [0, 1]],
    triangles[:, [1, 2]],
    triangles[:, [2, 0]]
])

edges = np.sort(edges, axis=1)

unique_edges = np.unique(edges, axis=0)

print(unique_edges)


[[0 1]
 [0 2]
 [0 3]
 [0 8]
 [0 9]
 [1 2]
 [1 3]
 [1 4]
 [2 3]
 [3 4]
 [3 5]
 [4 5]
 [4 6]
 [5 6]
 [5 7]
 [6 7]
 [6 8]
 [7 8]
 [7 9]
 [8 9]]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [60]:
import numpy as np

C = np.array([0, 2, 1, 4]) 

A = np.repeat(np.arange(len(C)), C)

print(A)         
print(np.bincount(A))



[1 1 2 3 3 3 3]
[0 2 1 4]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [1]:
import numpy as np
x = np.array([1, 2, 3, 4, 5, 6])
window = 3

kernel = np.ones(window)/window

avg = np.convolve(x,kernel, mode='valid')
print(avg)

[2. 3. 4. 5.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [2]:
import numpy as np

Z = np.array([1, 2, 3, 4,5,6])
res = np.lib.stride_tricks.sliding_window_view(Z,3)
print(res)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [18]:
Z = np.array([-1.0,2.5,-5.0])
np.negative(Z, out=Z)
print(Z)


[ 1.  -2.5  5. ]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)